### ISSUE TITLE
problem with audiobook.py 

### ISSUE THREAD

**Issue by Gautamhirawat** [I-Ishika-012/Projects#1]
Greetings , 

i have found an error in your this audiobook.py , 

1>

``pdf_File = open(r"C:\Users\MAC\OneDrive\Documents\Chapter 1.pdf",'rb') 
``
it has specific path of a specific file named Chapter 1.pdf , followed by this  it can pe possible that one might not save his/her file to same location thus it can create a error in the terminal . 

Instead if that you can use :- 

   ```
 from tkinter import Tk, filedialog
      def get_pdf_file_path():
       root = Tk()
         root.withdraw()  
     file_path = filedialog.askopenfilename(
         title="Select PDF File",
         filetypes=[("PDF files", "*.pdf"), ("All files", "*.*")]
     )
     root.destroy() 
     return file_path
     pdf_file_path = get_pdf_file_path()
```

you can make a function ... that can take files from your device. 

2>
If there is image in the pdf , genarallly pdf have first page as the image so genrally it will show error . 
you can add try - catch to solve major part . and also you should lable that only text pdf is applicable to this audiobook.py 

Regards

**Comment by I-Ishika-012** [comment]
Thanks for raising an issue; I'll carry out the fixes soon. And yes I am
aware this throws an error for any other media content than text but never
mentioned it but I'll still be making necessary changes.
Thanks and Regards
I-Ishika-012
